name: PR Author Stats
on:
  pull_request:
    types: [opened]

jobs:
  analyze-pr-author:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install @octokit/rest typescript @types/node

      - name: Run PR Analysis
        uses: actions/github-script@v7
        with:
          script: |
            const { analyzePRAndComment } = require('./scripts/analyze.js');
            await analyzePRAndComment(github, context);
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }} # Pass the GitHub token as environment variable
